name: CD Front-end

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Install Dependencies
        working-directory: sgcmapp/
        run: |
          npm install --legacy-peer-deps

      - name: Build
        working-directory: sgcmapp/
        run: npm run build

      - name: Deploy to Vercel
        working-directory: sgcmapp/
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --prod
